aerial_robot_control_name: aerial_robot_control/fullbody_flight_controller

controller:
  gimbal_delta_max: 3.14  # Maximum change in gimbal angles (radians)


ddp:
  num_threads: 4
  horizon: 2.0
  dt: 0.05
  fwddyn: false
  max_iter: 100
