robot_model_plugin_name: aerial_robot_model/manipulator_robot_model
model:
  rotor_devider: 1

dynamics:
  is_floating_base: true

  hessian_trace: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                  0.01, 0.01, 1.0, 1.0,
                  0.01, 0.01, 1.0, 1.0,
                  0.01, 0.01, 1.0, 1.0,
                  0.01, 0.01,
                  0.1, 0.1, 0.1, 0.1,
                  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
