servo_controller:

  joints:
    # for low pass filter
    filter_flag: true
    sample_freq: 50.0 # 50Hz
    cutoff_freq: 10.0 # 10Hz, test

    # for simulation
    simulation:
      pid: {p: 200.0, i: 0.0, d: 10.0}
      init_value: 0.0
      type: effort_controllers/JointComputeTorqueController

    controller1:
      name: joint1
    controller2:
      name: joint2
    controller3:
      name: joint3

  gimbals:
    simulation:
      pid: {p: 50.0, i: 0.01, d: 0.0}
      init_value: 0.0
      type: effort_controllers/JointPositionController

    controller1:
      name: gimbal1_roll
    controller2:
      name: gimbal1_pitch
    controller3:
      name: gimbal2_roll
    controller4:
      name: gimbal2_pitch
